// LAB 9.1.1

/** This script is executed before the Record is generated
 * `current`- GlideRecord produced by Record Producer
 * Don't use `current.update()` or `current.insert()` as the record is generated by Record Producer
 * Don't use `current.setValue('sys_class_name', 'xxx')` as this will trigger reparent flow and can cause data loss
 * Avoid `current.setAbortAction()` and generate a separate record
 * Use `producer.var1` to access variables
 */

// Set the short description to reflect the item type and location

current.short_description =
  "Reservation: " +
  current.item_type.getDisplayValue() +
  " from " +
  current.depot.getDisplayValue();

// Set the depot field to reflect inputs from the record producer

current.depot = producer.depot;
if (producer.depot == "Other") {
  current.other = producer.other;
}

// Set the initial state to Requested

current.state = 13;
